version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"    # Jenkins web arayüzü
      - "50000:50000"  # Agent bağlantıları için port
    volumes:
      - jenkins_home:/var/jenkins_home  # Jenkins verilerinin kalıcılığı
    restart: unless-stopped

volumes:
  jenkins_home: